#Lab4:Interaction Terms, MSCS3045, Fall2022.


The objective of this lab is learn about how to make multiple linear regression.
You can find more information about the data used in this lab here: https://www.kaggle.com/datasets/elikplim/forest-fires-data-set



The forestfires.csv data base contains information on 517 forest fires that occurred in Montesinho Natural Park in Portugal. The columns report the temperature, relative humidity, wind speed, and amount of rainfall at the time of the fire, as well as the area burned.

1. Read in the file forestfires.csv.
2. Perform multiple linear regression using the ols() function with area as the response variable and wind and the interaction term RH*temp, in that order, as the predictor variables.
3. Create and print the ANOVA table.
                sum_sq     df         F    PR(>F)
wind      3.205248e+03    1.0  0.795656  0.372814
RH        1.417655e+03    1.0  0.351912  0.553295
temp      1.149237e+04    1.0  2.852813  0.091823
RH:temp   4.240945e+03    1.0  1.052752  0.305359
Residual  2.062559e+06  512.0       NaN       NaN

4. If rain is used instead of wind, the output is:


                sum_sq     df         F    PR(>F)
rain      1.239028e+01    1.0  0.003071  0.955829
RH        1.435916e+03    1.0  0.355894  0.551059
temp      9.949932e+03    1.0  2.466107  0.116943
RH:temp   3.238244e+03    1.0  0.802604  0.370737
Residual  2.065752e+06  512.0       NaN       NaN
'

In [34]:
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from statsmodels.formula.api import ols

# 1. read in the file Forestfires.csv

df = pd.read_csv('/content/forestfires.csv')
df

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [35]:

#2. perform multiple linear regression using the ols() function with area as the response variable and wind and the interaction term RH*temp, in that order, as the predictor variables.

lm = ols('area ~ wind + RH + temp + RH:temp', data=df).fit()
print(lm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   area   R-squared:                       0.014
Model:                            OLS   Adj. R-squared:                  0.006
Method:                 Least Squares   F-statistic:                     1.757
Date:                Fri, 11 Nov 2022   Prob (F-statistic):              0.136
Time:                        20:16:59   Log-Likelihood:                -2876.9
No. Observations:                 517   AIC:                             5764.
Df Residuals:                     512   BIC:                             5785.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -25.2818     27.734     -0.912      0.362     -79.768      29.205
wind           1.4423      1.617      0.892      0.373      -1.734       4.619
RH             0.3178      0.472      0.673      0.501      -0.609       1.245
temp           2.1519      1.280      1.681      0.093      -0.363       4.667
RH:temp       -0.0285      0.028     -1.026      0.305      -0.083       0.026
==============================================================================
Omnibus:                      975.473   Durbin-Watson:                   1.637
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           776668.658
Skew:                          12.586   Prob(JB):                         0.00
Kurtosis:                     191.204   Cond. No.                     8.25e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.25e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [36]:
#3. print the ANOVA table
anova_table = anova_lm(lm)
print(anova_table)

             df        sum_sq       mean_sq         F    PR(>F)
wind        1.0  3.172162e+02    317.216174  0.078744  0.779120
RH          1.0  1.225487e+04  12254.871384  3.042092  0.081731
temp        1.0  1.149237e+04  11492.373827  2.852813  0.091823
RH:temp     1.0  4.240945e+03   4240.944730  1.052752  0.305359
Residual  512.0  2.062559e+06   4028.435972       NaN       NaN

In [37]:
#4. If rain is used instead of wind
lm1 = ols('area ~ rain + RH + temp + RH:temp', data=df).fit()
print(lm1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   area   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     1.556
Date:                Fri, 11 Nov 2022   Prob (F-statistic):              0.185
Time:                        20:16:59   Log-Likelihood:                -2877.3
No. Observations:                 517   AIC:                             5765.
Df Residuals:                     512   BIC:                             5786.
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -14.7288     25.124     -0.586      0.558     -64.087      34.629
rain          -0.5409      9.761     -0.055      0.956     -19.717      18.635
RH             0.2571      0.470      0.547      0.584      -0.666       1.180
temp           1.9029      1.258      1.513      0.131      -0.569       4.374
RH:temp       -0.0251      0.028     -0.896      0.371      -0.080       0.030
==============================================================================
Omnibus:                      976.230   Durbin-Watson:                   1.645
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           779466.041
Skew:                          12.607   Prob(JB):                         0.00
Kurtosis:                     191.543   Cond. No.                     7.46e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.46e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [38]:
# print the ANOVA table
from statsmodels.stats.anova import anova_lm
anova_table1 = anova_lm(lm1)
print(anova_table1)

             df        sum_sq       mean_sq         F    PR(>F)
rain        1.0  1.134377e+02    113.437702  0.028116  0.866903
RH          1.0  1.181093e+04  11810.934099  2.927359  0.087696
temp        1.0  9.949932e+03   9949.932346  2.466107  0.116943
RH:temp     1.0  3.238244e+03   3238.243853  0.802604  0.370737
Residual  512.0  2.065752e+06   4034.672023       NaN       NaN